type Coin = { [key: string]: string };
export const coins: Coin = {
  BTCUSDT: "bitcoin",
  ETHUSDT: "ethereum",
  BNBUSDT: "binancecoin",
  BCCUSDT: "bitcoincash",
  NEOUSDT: "neo",
  LTCUSDT: "litecoin",
  QTUMUSDT: "qtum",
  ADAUSDT: "cardano",
  XRPUSDT: "xrp",
  EOSUSDT: "eos",
  TUSDUSDT: "trueusd",
  IOTAUSDT: "iota",
  XLMUSDT: "stellar",
  ONTUSDT: "ontology",
  TRXUSDT: "tron",
  ETUSDT: "ethereumclassic",
  ICXUSDT: "icon",
  VENUSDT: "vechain",
  NULSUSDT: "nuls",
  VETUSDT: "vechaintoken",
  PAXUSDT: "paxosstandardtoken",
  BCHABCUSDT: "bitcoinabc",
  BCHSVUSDT: "bitcoinsv",
  USDCUSDT: "usdcoin",
  LINKUSDT: "chainlink",
  WAVESUSDT: "waves",
  BTTUSDT: "bittorrenttoken",
  USDSUSDT: "usdstablecoin",
  ONGUSDT: "ontologygas",
  HOTUSDT: "holo",
  ZILUSDT: "zilliqa",
  ZRXUSDT: "0x",
  FETUSDT: "fetchai",
  BATUSDT: "basicattentiontoken",
  XMRUSDT: "monero",
  ZECUSDT: "zcash",
  IOSTUSDT: "iost",
  CELRUSDT: "celernetwork",
  DASHUSDT: "dash",
  NANOUSDT: "nano",
  OMGUSDT: "omgnetwork",
  THETAUSDT: "thetanetwork",
  ENJUSDT: "enjincoin",
  MITHUSDT: "mithril",
  MATICUSDT: "polygon(matic)",
  ATOMUSDT: "cosmos(atom)",
  TFUELUSDT: "thetafuel",
  ONEUSDT: "harmony(one)",
  FTMUSDT: "fantom",
  ALGOUSDT: "algorand",
  USDSBUSDT: "usdstablecoin",
  GTOUSDT: "gifto",
  ERDUSDT: "elrond",
  DOGEUSDT: "dogecoin",
  DUSKUSDT: "dusknetwork",
  ANKRUSDT: "ankrnetwork",
  WINUSDT: "winklink",
  COSUSDT: "cosmos",
  NPXSUSDT: "pundix",
  COCOSUSDT: "cocos",
  MTLUSDT: "metal",
  TOMOUSDT: "tomochain",
  PERLUSDT: "perlin",
  DENTUSDT: "dent",
  MFTUSDT: "mainframe",
  KEYUSDT: "selfkey",
  STORMUSDT: "storm",
  DOCKUSDT: "dock",
  WANUSDT: "wanchain",
  FUNUSDT: "funtoken",
  CVCUSDT: "civic",
  CHZUSDT: "chiliz",
  BANDUSDT: "bandprotocol",
  BUSDUSDT: "binanceusd",
  BEAMUSDT: "beam",
  XTZUSDT: "tezos",
  RENUSDT: "ren",
  RVNUSDT: "ravencoin",
  HCUSDT: "huobitoken",
  HBARUSDT: "hederahashgraph",
  NKNUSDT: "nkn",
  STXUSDT: "stacks",
  KAVAUSDT: "kava",
  ARPAUSDT: "arpa chain",
  IOTXUSDT: "iotex",
  RLCUSDT: "rlc",
  MCOUSDT: "crypto.com coin",
  CTXCUSDT: "conflux network",
  BCHUSDT: "bitcoin cash",
  TROYUSDT: "troy",
  VITEUSDT: "vite",
  FTTUSDT: "ftx token",
  EURUSDT: "euro",
  OGNUSDT: "origin protocol",
  DREPUSDT: "drep",
  BULLUSDT: "binance leveraged token bull",
  BEARUSDT: "binance leveraged token bear",
  ETHBULLUSDT: "ethbull",
  ETHBEARUSDT: "ethbear",
  TCTUSDT: "tokenclub",
  WRXUSDT: "wazirx token",
  BTSUSDT: "bitshares",
  LSKUSDT: "lisk",
  BNTUSDT: "bancor network token",
  LTOUSDT: "linkeye",
  EOSBULLUSDT: "eosbull",
  EOSBEARUSDT: "eosbear",
  XRPBULLUSDT: "xrpbull",
  XRPBEARUSDT: "xrpbear",
  STRATUSDT: "stratis",
  AIONUSDT: "aion",
  MBLUSDT: "mobilecoin",
  COTIUSDT: "coti",
  BNBBULLUSDT: "bnbbull",
  BNBBEARUSDT: "bnbbear",
  STPTUSDT: "stpt",
  WTCUSDT: "waltonchain",
  DATAUSDT: "dora factory",
  XZCUSDT: "zcoin",
  SOLUSDT: "solana",
  CTSIUSDT: "cartesi",
  HIVEUSDT: "hive",
  CHRUSDT: "chromia",
  BTCUPUSDT: "btcup",
  BTCDOWNUSDT: "btcdown",
  GXSUSDT: "gxchain",
  ARDRUSDT: "ardor",
  LENDUSDT: "aave",
  MDTUSDT: "mdex",
  STMXUSDT: "stormx",
  KNCUSDT: "kyber network crystal",
  REPUSDT: "augur",
  LRCUSDT: "loopring",
  PNTUSDT: "penta",
  COMPUSDT: "compound",
  BKRWUSDT: "krw",
  SCUSDT: "siacoin",
  ZENUSDT: "horizen",
  SNXUSDT: "synthetix",
  ETHUPUSDT: "ethup",
  ETHDOWNUSDT: "ethdown",
  ADAUPUSDT: "adaup",
  ADADOWNUSDT: "adadown",
  LINKUPUSDT: "linkup",
  LINKDOWNUSDT: "linkdown",
  VTHOUSDT: "vtho",
  DGBUSDT: "digibyte",
  GBPUSDT: "british pound sterling",
  SXPUSDT: "swipe",
  MKRUSDT: "maker",
  DAIUSDT: "dai",
  DCRUSDT: "decred",
  STORJUSDT: "storj",
  BNBUPUSDT: "bnbup",
  BNBDOWNUSDT: "bnbdown",
  XTZUPUSDT: "xtzup",
  XTZDOWNUSDT: "xtzdown",
  MANAUSDT: "decentraland",
  AUDUSDT: "australian dollar",
  YFIUSDT: "yearn.finance",
  BALUSDT: "balancer",
  BLZUSDT: "bluzelle",
  IRISUSDT: "irisnet",
  KMDUSDT: "komodo",
  JSTUSDT: "just",
  SRMUSDT: "serum",
  ANTUSDT: "aragon",
  CRVUSDT: "curve dao token",
  SANDUSDT: "the sandbox",
  OCEANUSDT: "ocean protocol",
  NMRUSDT: "numeraire",
  DOTUSDT: "polkadot",
  LUNAUSDT: "terra",
  RSRUSDT: "reserve rights",
  PAXGUSDT: "pax gold",
  WNXMUSDT: "wrapped nxm",
  TRBUSDT: "tellor",
  BZRXUSDT: "bzx protocol token",
  SUSHIUSDT: "sushiswap",
  YFIIUSDT: "yearn.finance",
  KSMUSDT: "kusama",
  EGLDUSDT: "elrond",
  DIAUSDT: "dia",
  RUNEUSDT: "thorchain",
  FIOUSDT: "fio protocol",
  UMAUSDT: "uma",
};
